const $=s=>document.querySelector(s); const app=$('#app');
const state={route:'home',module:'all',training:'flash',flashIndex:0,flashFace:'front',qIndex:0,clozeIndex:0,caseIndex:0};
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let favorites=store.get('favorites',[]), reviews=store.get('reviews',{});

function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nav(route){state.route=route; render(); window.scrollTo({top:0,behavior:'smooth'})}
function moduleName(id){return KB.modules.find(x=>x.id===id)?.name||id}
function priority(n){return '★'.repeat(n)+'☆'.repeat(3-n)}
function bindNav(){document.querySelectorAll('.nav-btn').forEach(b=>{b.classList.toggle('active',b.dataset.route===state.route);b.onclick=()=>nav(b.dataset.route)})}
function render(){bindNav(); if(state.route==='home')home(); if(state.route==='fiches')fiches(); if(state.route==='training')training(); if(state.route==='tools')tools();}

function home(){
  const card=KB.flashcards[new Date().getDate()%KB.flashcards.length];
  app.innerHTML=`<section class="hero"><h2>Le bon réflexe, au bon moment.</h2><p>${KB.fiches.length} fiches de base • données vérifiées au ${KB.verifiedAt.split('-').reverse().join('/')} • progression locale</p><div class="search"><input id="homeSearch" placeholder="Ex. ZFANG, TVA, SAS, 244 quater W…" /></div></section>
  <div class="section-head"><div><h2>Domaines</h2><p>Choisir un thème de travail</p></div></div><section class="grid">${KB.modules.map(m=>`<button class="module-card" data-module="${m.id}"><div class="emoji">${m.emoji}</div><h3>${m.name}</h3><p>${m.desc}</p></button>`).join('')}</section>
  <div class="section-head"><div><h2>Réflexe du jour</h2><p>30 secondes pour consolider un automatisme</p></div></div><section class="card daily"><span class="badge">🧠 MÉMOIRE</span><div class="prompt">${esc(card[0])}</div><button class="secondary" id="dailyReveal">Afficher la réponse</button><div class="answer hidden" id="dailyAnswer">${esc(card[1])}</div></section>
  <div class="section-head"><div><h2>À connaître en priorité</h2></div><button class="link-btn" id="seeFiches">Tout voir →</button></div><section class="fiches-list">${KB.fiches.filter(f=>f.priority===3).slice(0,4).map(f=>ficheRow(f)).join('')}</section>`;
  $('#dailyReveal').onclick=()=>$('#dailyAnswer').classList.remove('hidden'); $('#seeFiches').onclick=()=>nav('fiches');
  document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>{state.module=b.dataset.module;nav('fiches')});
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openFiche(b.dataset.open));
  $('#homeSearch').addEventListener('input',e=>{ if(e.target.value.trim().length>1){state.module='all';state.route='fiches';render(); setTimeout(()=>{const i=$('#searchFiches');i.value=e.target.value;filterFiches()},0)} });
}
function ficheRow(f){return `<article class="card fiche-row" data-open="${f.id}"><div><span class="badge">${moduleName(f.module)}</span><h3>${esc(f.title)}</h3><p>${esc(f.reflex)}</p><div class="priority">${priority(f.priority)} • ${esc(f.article)}</div></div><button class="star" data-star="${f.id}" aria-label="Favori">${favorites.includes(f.id)?'★':'☆'}</button></article>`}
function fiches(){
  app.innerHTML=`<section class="hero"><h2>Fiches de référence</h2><p>Résumé opérationnel, détail, pièges, exemples et sources officielles.</p><div class="search"><input id="searchFiches" placeholder="Rechercher une notion…" /></div></section><div class="filters" id="filters"><button class="chip ${state.module==='all'?'active':''}" data-filter="all">Tout</button>${KB.modules.map(m=>`<button class="chip ${state.module===m.id?'active':''}" data-filter="${m.id}">${m.emoji} ${m.name}</button>`).join('')}<button class="chip ${state.module==='fav'?'active':''}" data-filter="fav">★ Favoris</button></div><section class="fiches-list" id="fichesList"></section>`;
  document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.module=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));filterFiches()});
  $('#searchFiches').oninput=filterFiches; filterFiches();
}
function filterFiches(){const q=($('#searchFiches')?.value||'').toLowerCase().trim(); let arr=KB.fiches.filter(f=>state.module==='all'||(state.module==='fav'?favorites.includes(f.id):f.module===state.module)); if(q)arr=arr.filter(f=>[f.title,f.article,f.reflex,...f.tags].join(' ').toLowerCase().includes(q)); $('#fichesList').innerHTML=arr.length?arr.map(ficheRow).join(''):'<div class="card empty">Aucune fiche trouvée.</div>'; document.querySelectorAll('[data-open]').forEach(r=>r.onclick=e=>{if(e.target.dataset.star)return;openFiche(r.dataset.open)}); document.querySelectorAll('[data-star]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.star);filterFiches()})}
function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];store.set('favorites',favorites)}
function openFiche(id){const f=KB.fiches.find(x=>x.id===id); state.route='fiche'; bindNav(); app.innerHTML=`<button class="back" id="backFiches">← Retour aux fiches</button><section class="card fiche-hero"><div><span class="badge">${moduleName(f.module)}</span> <span class="badge ${f.status.includes('2026')?'warn':''}">${esc(f.status)}</span></div><h2>${esc(f.title)}</h2><div class="meta"><span>${esc(f.article)}</span><span>•</span><span>Vérifié ${KB.verifiedAt.split('-').reverse().join('/')}</span><span>•</span><span>${priority(f.priority)}</span></div><div class="reflex">⚡ ${esc(f.reflex)}</div></section>
  <section class="card content-card"><h3>Questions à poser au client</h3><ul>${f.ask.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
  <section class="card content-card"><h3>Comprendre</h3><ul>${f.detail.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
  <section class="card content-card trap"><h3>⚠️ Piège classique</h3><p>${esc(f.trap)}</p></section>
  <section class="card content-card example"><h3>💼 Exemple cabinet</h3><p>${esc(f.example)}</p></section>
  <section class="card content-card"><h3>Sources officielles</h3>${f.sources.map(s=>`<a class="source" href="${s[1]}" target="_blank" rel="noopener">↗ ${esc(s[0])}</a>`).join('')}<p class="fineprint">Outil pédagogique : avant de conseiller ou déclarer, vérifier le texte applicable à la période et à la situation exacte du client.</p></section>`; $('#backFiches').onclick=()=>{state.route='fiches';render()};}

function training(){app.innerHTML=`<section class="hero"><h2>Entraînement</h2><p>Répétition active : cartes, QCM, textes à trous et cas clients.</p></section><div class="tabs"><button data-tab="flash" class="${state.training==='flash'?'active':''}">Cartes</button><button data-tab="qcm" class="${state.training==='qcm'?'active':''}">QCM</button><button data-tab="cloze" class="${state.training==='cloze'?'active':''}">Trous</button><button data-tab="cases" class="${state.training==='cases'?'active':''}">Cas</button></div><div id="trainingPane"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.training=b.dataset.tab;training()});renderTrainingPane()}
function renderTrainingPane(){if(state.training==='flash')flash();if(state.training==='qcm')qcm();if(state.training==='cloze')cloze();if(state.training==='cases')cases()}
function flash(){const i=state.flashIndex%KB.flashcards.length,c=KB.flashcards[i],front=state.flashFace==='front';const known=Object.values(reviews).filter(x=>x==='know').length;$('#trainingPane').innerHTML=`<div class="progress"><span style="width:${((i+1)/KB.flashcards.length)*100}%"></span></div><section class="card training-card flip" id="flip"><div class="kicker">CARTE ${i+1}/${KB.flashcards.length}</div><h2>${esc(front?c[0]:c[1])}</h2><p>${front?'Touchez la carte pour révéler la réponse.':'Évaluez votre rappel, puis passez à la suivante.'}</p></section>${front?'':`<div class="rating"><button class="choice miss" data-rate="miss">× À revoir</button><button class="choice know" data-rate="know">✓ Je sais</button></div>`}<p class="fineprint">Connues : ${known} • Progression enregistrée sur cet appareil.</p>`;$('#flip').onclick=()=>{state.flashFace=front?'back':'front';flash()};document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{reviews[i]=b.dataset.rate;store.set('reviews',reviews);state.flashIndex=(i+1)%KB.flashcards.length;state.flashFace='front';flash()})}
function qcm(){const i=state.qIndex%KB.qcm.length,q=KB.qcm[i];$('#trainingPane').innerHTML=`<div class="progress"><span style="width:${((i+1)/KB.qcm.length)*100}%"></span></div><section class="card training-card"><div class="kicker">QCM ${i+1}/${KB.qcm.length}</div><h2>${esc(q.q)}</h2><div class="choices">${q.a.map((x,j)=>`<button class="choice" data-choice="${j}">${esc(x)}</button>`).join('')}</div><div id="feedback"></div></section>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const j=+b.dataset.choice;document.querySelectorAll('[data-choice]').forEach((x,k)=>{x.disabled=true;if(k===q.good)x.classList.add('good');if(k===j&&j!==q.good)x.classList.add('bad')});$('#feedback').innerHTML=`<div class="answer">${j===q.good?'✓ Correct.':'× Pas tout à fait.'} ${esc(q.why)}</div><button class="primary" id="nextQ" style="margin-top:12px">Question suivante</button>`;$('#nextQ').onclick=()=>{state.qIndex=(i+1)%KB.qcm.length;qcm()}})}
function cloze(){const i=state.clozeIndex%KB.cloze.length,c=KB.cloze[i];$('#trainingPane').innerHTML=`<div class="progress"><span style="width:${((i+1)/KB.cloze.length)*100}%"></span></div><section class="card training-card"><div class="kicker">TEXTE À TROUS ${i+1}/${KB.cloze.length}</div><h2>${esc(c.text)}</h2><div class="field"><input id="clozeInput" placeholder="Votre réponse…" autocomplete="off"></div><button class="primary" id="checkCloze">Vérifier</button><div id="feedback"></div></section>`;$('#checkCloze').onclick=()=>{const v=$('#clozeInput').value.trim().toLowerCase().replace('%','');const a=c.answer.toLowerCase();const ok=v===a||a.includes(v)&&v.length>2;$('#feedback').innerHTML=`<div class="answer">${ok?'✓ Correct.':'Réponse : '+esc(c.answer)}</div><button class="secondary" id="nextCloze" style="margin-top:12px">Suivant</button>`;$('#nextCloze').onclick=()=>{state.clozeIndex=(i+1)%KB.cloze.length;cloze()}}}
function cases(){const i=state.caseIndex%KB.cases.length,c=KB.cases[i];$('#trainingPane').innerHTML=`<div class="progress"><span style="width:${((i+1)/KB.cases.length)*100}%"></span></div><section class="card training-card"><div class="kicker">CAS CLIENT ${i+1}/${KB.cases.length}</div><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p><button class="primary" id="revealCase">Quels réflexes fallait-il avoir ?</button><div id="caseAns"></div></section>`;$('#revealCase').onclick=()=>{$('#caseAns').innerHTML=`<div class="answer" style="text-align:left"><ul>${c.points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><button class="secondary" id="nextCase" style="margin-top:12px">Cas suivant</button>`;$('#nextCase').onclick=()=>{state.caseIndex=(i+1)%KB.cases.length;cases()}}}

function tools(){app.innerHTML=`<section class="hero"><h2>Outils de raisonnement</h2><p>Simuler pour comprendre. Les résultats sont pédagogiques et doivent être validés sur le dossier réel.</p></section><section class="tool-grid"><article class="card tool-card"><h3>🧮 Résultat fiscal</h3><p>Classer des retraitements et voir le passage comptable → fiscal.</p><button class="primary" id="openFiscalTool">Ouvrir le simulateur</button></article><article class="card tool-card"><h3>🌳 SAS ou SARL ?</h3><p>Un arbre pédagogique pour identifier les critères qui changent le raisonnement.</p><button class="primary" id="openDecision">Lancer l’arbre</button></article><article class="card tool-card"><h3>🌴 Réflexe investissement DOM</h3><p>Checklist avant de conclure qu’un investissement ouvre droit au 244 quater W.</p><button class="primary" id="openInvest">Ouvrir la checklist</button></article></section><div id="toolPane"></div>`;$('#openFiscalTool').onclick=fiscalTool;$('#openDecision').onclick=decisionTool;$('#openInvest').onclick=investTool}
function fiscalTool(){const items=[['Amende et pénalité',800,'add'],['Dépense personnelle du dirigeant',400,'add'],['Provision non déductible',3000,'add'],['Produit comptable exonéré',5000,'sub'],['Charge courante justifiée',12000,'none']];$('#toolPane').innerHTML=`<section class="card content-card" style="margin-top:14px"><h3>Simulateur de résultat fiscal</h3><div class="field"><label>Résultat comptable</label><input type="number" id="accounting" value="75000"></div>${items.map((x,i)=>`<div class="adjustment"><div><strong>${x[0]}</strong><br><small>${x[1].toLocaleString('fr-FR')} €</small></div><select class="treat" data-amount="${x[1]}"><option value="none">Aucun</option><option value="add">Réintégration</option><option value="sub">Déduction</option></select></div>`).join('')}<div class="result-box">Résultat fiscal : <strong id="fiscalResult">75 000 €</strong><br><small id="fiscalDetail">+ 0 € − 0 €</small></div><button class="secondary" id="correction" style="margin-top:12px">Afficher la correction-type</button><div id="corr" class="hidden answer"></div><p class="fineprint">Exercice pédagogique : dans un dossier réel, le traitement dépend des faits, des pièces et du texte applicable.</p></section>`;const calc=()=>{let r=+$('#accounting').value||0,a=0,s=0;document.querySelectorAll('.treat').forEach(x=>{const n=+x.dataset.amount;if(x.value==='add')a+=n;if(x.value==='sub')s+=n});$('#fiscalResult').textContent=(r+a-s).toLocaleString('fr-FR')+' €';$('#fiscalDetail').textContent=`+ ${a.toLocaleString('fr-FR')} € − ${s.toLocaleString('fr-FR')} €`};$('#accounting').oninput=calc;document.querySelectorAll('.treat').forEach((x,i)=>{x.onchange=calc});$('#correction').onclick=()=>{document.querySelectorAll('.treat').forEach((x,i)=>x.value=items[i][2]);calc();$('#corr').classList.remove('hidden');$('#corr').textContent='Correction : amende, dépense personnelle et provision non déductible → réintégrations ; produit exonéré → déduction ; charge courante justifiée → aucun retraitement.'}}
function decisionTool(){const pane=$('#toolPane');const questions=[{q:'Le dirigeant sera-t-il majoritaire et veut-il surtout comparer le régime social de sa rémunération ?',yes:1,no:2},{q:'Le régime TNS est-il acceptable après simulation 2026 de la protection et du net disponible ?',yes:3,no:4},{q:'La souplesse statutaire et l’entrée future d’investisseurs sont-elles des enjeux importants ?',yes:4,no:5}];let step=0;function draw(){if(step<questions.length){let q=questions[step];pane.innerHTML=`<section class="card decision-step" style="margin-top:14px"><span class="badge">ARBRE PÉDAGOGIQUE</span><h3>${esc(q.q)}</h3><div class="decision-actions"><button class="choice" data-a="yes">Oui</button><button class="choice" data-a="no">Non / pas spécialement</button></div></section>`;document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{step=b.dataset.a==='yes'?q.yes:q.no;draw()})}else{const text=step===3?'La SARL mérite une simulation approfondie : gérance majoritaire TNS, cadre légal plus structuré, effets sociaux des dividendes à contrôler.':step===4?'La SAS mérite une simulation approfondie : président assimilé salarié, souplesse statutaire et actions souvent adaptées à l’entrée d’investisseurs.':'Aucun choix ne s’impose : comparez au moins rémunération, protection sociale, dividendes, gouvernance, cession et coût administratif.';pane.innerHTML=`<section class="card content-card" style="margin-top:14px"><h3>Résultat de l’arbre</h3><div class="recommend">${text}</div><p class="fineprint">Ce résultat n’est pas une recommandation juridique automatique : il indique la structure à SIMULER en priorité.</p><button class="secondary" id="restart">Recommencer</button></section>`;$('#restart').onclick=()=>{step=0;draw()}}}draw()}
function investTool(){$('#toolPane').innerHTML=`<section class="card content-card" style="margin-top:14px"><h3>Checklist 244 quater W</h3><p>Cochez ce que vous avez déjà sécurisé :</p>${['Entreprise imposée au réel / situation admise','Investissement réalisé dans un DOM','Bien productif et neuf','Activité éligible','Bien affecté à l’exploitation éligible','Coût HT et frais amortissables identifiés','Aides publiques identifiées','Agrément préalable vérifié si nécessaire'].map((x,i)=>`<label class="adjustment"><span>${x}</span><input type="checkbox" class="investcheck"></label>`).join('')}<div class="result-box" id="investResult">0 / 8 contrôles réalisés</div><p class="fineprint">Une checklist complète ne prouve pas l’éligibilité : elle évite surtout d’oublier les questions structurantes avant l’investissement.</p></section>`;const c=()=>{$('#investResult').textContent=`${document.querySelectorAll('.investcheck:checked').length} / 8 contrôles réalisés`};document.querySelectorAll('.investcheck').forEach(x=>x.onchange=c)}


function setupIOSInstallTip(){
  const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.platform==='MacIntel' && navigator.maxTouchPoints>1);
  const standalone=window.matchMedia('(display-mode: standalone)').matches || navigator.standalone===true;
  const dismissed=store.get('iosInstallTipDismissed',false);
  const tip=document.querySelector('#iosInstallTip');
  if(tip && isIOS && !standalone && !dismissed){
    tip.classList.remove('hidden');
    const close=document.querySelector('#dismissInstallTip');
    if(close) close.onclick=()=>{tip.classList.add('hidden');store.set('iosInstallTipDismissed',true)};
  }
}

$('#themeBtn').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;store.set('theme',t)};document.documentElement.dataset.theme=store.get('theme','light');
if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
setupIOSInstallTip();
