window.CRYPTO_V3={
competencies:[
{id:"accounting",name:"Comptabilité",modules:["C08","C09","C10","C11","C12","C13","C14","C19","C20","C24","A01"]},
{id:"tax",name:"Fiscalité / IS",modules:["C15","C18","C19","C20","C21","A02","A03"]},
{id:"vat",name:"TVA",modules:["C16","C23","C24"]},
{id:"regulation",name:"MiCA & déclaratif",modules:["C05","C17","C28"]},
{id:"data",name:"Données & audit",modules:["C02","C03","C06","C07","C13","C14","C22"]},
{id:"defi",name:"DeFi & opérations avancées",modules:["C19","C20","C21","C22","C23","C24","A03"]},
{id:"mission",name:"Conduite de mission",modules:["C25","C26","C27","C29","C30"]}
],
quizzes:{
C01:[["Être compétent signifie surtout…",["avoir tout lu","savoir qualifier, appliquer, documenter et reconnaître ses limites","connaître les cours crypto"],1],["Un module lu est-il automatiquement maîtrisé ?",["oui","non"],1]],
C03:[["Un wallet au nom du dirigeant prouve-t-il la propriété de la SAS ?",["oui","non, il faut établir les droits de la société"],1],["La seed phrase doit-elle être copiée dans le dossier permanent ?",["oui","non"],1]],
C04:[["Le nom commercial d'un token suffit-il à son classement ?",["oui","non, les droits priment"],1],["Un stablecoin est-il toujours un EMT ?",["oui","non"],1]],
C08:[["Le classement dépend notamment…",["uniquement du prix","des droits et de l'intention documentée","du logo du token"],1],["Deux entités doivent-elles toujours classer le même token pareil ?",["oui","pas nécessairement"],1]],
C11:[["Une baisse latente sur un actif 522 se limite-t-elle à D4742/C522 ?",["oui","non, le traitement du risque/provisionnement doit aussi être analysé"],1]],
C15:[["Le résultat comptable crypto est-il automatiquement le résultat fiscal ?",["oui","non"],1],["Pourquoi suivre les provisions réintégrées ?",["pour éviter une double imposition lors de la reprise","pour calculer la TVA"],0]],
C16:[["Une prestation payée en BTC perd-elle son régime TVA propre ?",["oui","non"],1],["Paiement crypto et qualification TVA sont-ils le même sujet ?",["oui","non"],1]],
C17:[["DAC8 remplace-t-il les obligations propres du contribuable ?",["oui","non"],1]],
C19:[["Une restitution obligatoire d'actifs équivalents peut-elle influencer l'analyse d'un prêt ?",["oui","non"],0]],
C20:[["Une perte relative dans un pool est-elle automatiquement une perte comptable ?",["oui","non"],1]],
C23:[["Un NFT est-il une immobilisation corporelle par définition ?",["oui","non, il faut qualifier le droit représenté"],1]],
C25:[["Le nombre de transactions suffit-il à fixer un forfait ?",["oui","non"],1]],
C26:[["Un score blockchain nul remplace-t-il les diligences LCB-FT ?",["oui","non"],1]],
C29:[["Le meilleur test de compétence est…",["le nombre de pages lues","un dossier traçable et révisable","le temps passé"],1]],
C02:[["Une donnée on-chain prouve-t-elle seule le propriétaire économique ?",["oui","non"],1],["Un hash correspond-il toujours à un seul mouvement comptable ?",["oui","non"],1],["Quel élément faut-il conserver ?",["hash, réseau et source","uniquement une capture"],0]],
C05:[["Quel corpus répond d'abord au traitement comptable français ?",["MiCA","ANC/PCG","DAC8"],1],["Faut-il dater les textes utilisés ?",["oui","non"],0],["Tenir la comptabilité d'un détenteur est-il automatiquement un service MiCA ?",["oui","non"],1]],
C06:[["Avant transformation des exports, il faut…",["conserver les bruts","les supprimer"],0],["Un solde initial sans historique doit-il être valorisé à zéro ?",["oui","non"],1],["Quel contrôle détecte un historique incomplet ?",["pagination et trous de période","couleur du logo"],0]],
C07:[["Équation de quantité correcte ?",["ouverture + entrées - sorties - frais = clôture","entrées + prix = clôture"],0],["Un transfert interne est-il automatiquement une cession ?",["oui","non"],1],["Les virements bancaires vers exchanges doivent-ils être rapprochés ?",["oui","non"],0]],
C09:[["Un calcul de plus-value fiable exige d'abord…",["des quantités rapprochées","un cours au hasard"],0],["Les frais doivent-ils être distingués des unités transférées ?",["oui","non"],0],["La méthode de coût doit-elle être reproductible ?",["oui","non"],0]],
C10:[["Un swap crypto/crypto est-il forcément neutre car aucun euro ne transite ?",["oui","non"],1],["Un paiement fournisseur en crypto comporte…",["seulement une cession crypto","l'opération fournisseur et le règlement crypto"],1],["Les frais de transaction doivent-ils être ignorés ?",["oui","non"],1]],
C12:[["Le peg à 1 € suffit-il à qualifier un EMT ?",["oui","non"],1],["Un encaissement crypto change-t-il la nature du chiffre d'affaires ?",["oui","non"],1],["La clôture dépend-elle de la qualification retenue ?",["oui","non"],0]],
C13:[["Le dernier prix affiché est-il toujours une valeur fiable ?",["oui","non"],1],["Faut-il documenter heure et source du prix ?",["oui","non"],0],["Un blocage de retrait peut-il être pertinent pour l'évaluation ?",["oui","non"],0]],
C14:[["Quelle assertion vise la propriété ?",["droits et obligations","cut-off uniquement"],0],["Une capture isolée suffit-elle à prouver l'exhaustivité ?",["oui","non"],1],["Chaque chiffre significatif doit-il être traçable ?",["oui","non"],0]],
C18:[["Tous les airdrops ont-ils le même traitement ?",["oui","non"],1],["Quel réflexe vient en premier ?",["qualifier le droit et le fait générateur","appliquer un taux fiscal"],0],["Faut-il distinguer staking, cashback et referral ?",["oui","non"],0]],
C21:[["Un ratio 1:1 prouve-t-il l'identité des droits ?",["oui","non"],1],["Un bridge peut-il créer un risque de contrepartie/technique pertinent ?",["oui","non"],0],["Transformation et récompense doivent-elles être séparées ?",["oui","non"],0]],
C22:[["Retraits suspendus = perte définitive ?",["oui","non"],1],["Une perte de clé doit-elle être documentée comme irréversible avant conclusion ?",["oui","non"],0],["Le collatéral et les liquidations doivent-ils être compris avant comptabilisation ?",["oui","non"],0]],
C24:[["Une collecte contre services futurs est-elle toujours produit immédiat ?",["oui","non"],1],["Traitement comptable et conformité MiCA sont-ils deux analyses distinctes ?",["oui","non"],0],["Il faut d'abord identifier…",["les obligations de l'émetteur","le nombre de followers"],0]],
C27:[["Deux dossiers de 1 000 lignes ont-ils forcément le même coût ?",["oui","non"],1],["La qualité des données influence-t-elle le budget ?",["oui","non"],0],["Diagnostic et reprise peuvent-ils être facturés séparément ?",["oui","non"],0]],
C28:[["Les conclusions PCG se transposent-elles automatiquement en IFRS ?",["oui","non"],1],["Les actifs clients d'un conservateur sont-ils forcément ses actifs propres ?",["oui","non"],1],["Un client qui conserve des crypto-actifs pour autrui nécessite-t-il une analyse réglementaire spécifique ?",["oui","non"],0]],
C30:[["La progression locale est-elle une sauvegarde serveur ?",["oui","non"],1],["Faut-il stocker des clés privées dans les notes ?",["oui","non"],1],["Quelle routine est préférable ?",["lecture unique massive","étude, quiz, correction, révision, pratique"],1]],
A01:[["Quel livrable prouve l'exhaustivité des quantités ?",["rapprochement ouverture/entrées/sorties/frais/clôture","capture du cours"],0],["Une hausse latente est-elle automatiquement un produit de cession ?",["oui","non"],1],["L'atelier est-il validé si les calculs ne sont pas révisables ?",["oui","non"],1]],
A02:[["Une transition exige-t-elle d'identifier date et ancien/nouveau traitement ?",["oui","non"],0],["Les divergences fiscales pluriannuelles doivent-elles être suivies ?",["oui","non"],0],["Une incertitude doit-elle être cachée pour rendre le dossier plus propre ?",["oui","non"],1]],
A03:[["Le mot dépôt utilisé par une interface tranche-t-il la qualification ?",["oui","non"],1],["Un pool garantit-il la restitution des mêmes quantités ?",["toujours","pas nécessairement"],1],["Prêt et pool doivent-ils être comparés par les droits reçus ?",["oui","non"],0]]}
,traps:[
["Stablecoin = compte 513","Faux réflexe : qualifier d'abord juridiquement l'actif et les droits."],
["Wallet du dirigeant = actif de la société","Faux : documenter propriété, financement et contrôle."],
["Bridge 1:1 = neutralité garantie","Faux : comparer les droits avant/après et la substance."],
["Airdrop = produit automatiquement imposable à réception","Trop rapide : qualifier le droit et le fait générateur."],
["Pool DeFi = simple dépôt","Pas nécessairement : le jeton de position peut matérialiser d'autres droits."],
["Prix affiché = juste valeur exploitable","Pas toujours : liquidité, source, heure, restrictions et profondeur comptent."],
["DAC8 = déclaration fiscale de la société","Faux : distinguer reporting prestataire et obligations propres du contribuable."],
["NFT = immobilisation corporelle","Faux : analyser le droit économique représenté."],
["Score AML faible = dossier acceptable","Faux : l'outil ne remplace pas les diligences professionnelles."]
],
ledger:[
{q:"La SAS achète 1 BTC pour 50 000 € destiné à être conservé comme placement, hypothèse régime 522. Quelle logique ?",a:"Débiter le compte d'actifs numériques concerné pour le coût d'acquisition et créditer la trésorerie/compte de tiers selon le règlement. Traiter séparément les frais selon le référentiel et les faits."},
{q:"Un client règle une facture de conseil de 2 000 € en crypto. Quel réflexe ?",a:"Comptabiliser d'abord le chiffre d'affaires et la TVA selon la prestation ; comptabiliser distinctement l'entrée de crypto à sa valeur pertinente. Le moyen de paiement ne transforme pas la prestation en opération de change."},
{q:"À la clôture, la valeur d'un actif 522 est inférieure de 3 000 € à sa valeur comptable. Quel réflexe ?",a:"Appliquer le mécanisme de clôture prévu par le référentiel applicable, y compris l'écart d'évaluation et l'analyse/provisionnement du risque ; ne pas enregistrer une seule écriture isolée sans le schéma complet."}
],
realCaseSteps:["Acceptation et indépendance","Cartographie entités / wallets / exchanges","Collecte contrats et exports","Preuve des droits et propriété","Registre exhaustif des transactions","Rapprochement quantités et banque","Qualification des actifs et opérations","Écritures et valorisation de clôture","Passage comptable → fiscal","TVA et obligations déclaratives","LCB-FT / anomalies / pièces manquantes","Revue, annexe et restitution"],
pilotFields:["Contexte du dossier","Problématique professionnelle","Sources de données","Difficultés rencontrées","Contrôles mis en place","Outils / automatisations","Temps passé","Anomalies et résolution","Livrables produits","Enseignements pour le cabinet","Lien potentiel avec le mémoire DEC"]
};