// Enrichissement professionnel de toutes les fiches existantes — vérifié au 04/10/2026
(()=>{
  KB.verifiedAt='2026-10-04';
  const E=(id,data)=>{const f=KB.fiches.find(x=>x.id===id);if(f)Object.assign(f,data)};

  E('zfang',{
    status:'Cours professionnel — vérifié 2026',
    comparison:[['Question','Réflexe','Pourquoi'],['Taille','< 250 salariés et CA < 50 M€','Condition d’entrée à contrôler chaque exercice.'],['Activité','Tester l’éligibilité au regard de l’art. 199 undecies B','La localisation à La Réunion ne suffit pas.'],['Taux','50 % / plafond 150 k€ ou 80 % / plafond 300 k€ selon cas','Le taux majoré dépend du secteur ou de la localisation prévue par le texte.'],['2026 Réunion','Certaines communes bénéficient temporairement du renforcement à 80 %','Mesure temporaire liée à la loi de finances 2026.'],['Impôts locaux','CFE/TFPB ont leurs propres mécanismes','Ne pas extrapoler le taux “bénéfices” aux autres impôts.']],
    courseSections:[
      {title:'1. Champ d’application : raisonner exploitation par exploitation',paragraphs:['La ZFANG vise les bénéfices provenant d’exploitations situées dans les DOM, dont La Réunion. Le raisonnement se fait sur l’exploitation qui produit le bénéfice et non sur la seule adresse du siège social.','Les conditions de taille et d’activité doivent être contrôlées pour chaque exercice. Une entreprise réunionnaise peut être hors dispositif si son activité principale n’entre pas dans le champ éligible.'],bullets:['Effectif < 250 salariés.','CA annuel < 50 M€.','Activité principale éligible.','Régime d’imposition compatible.']},
      {title:'2. Calcul de l’abattement sur bénéfices',paragraphs:['Le régime de droit commun applique un abattement de 50 % aux bénéfices éligibles, dans la limite annuelle de 150 000 €. Le régime majoré porte le taux à 80 % et le plafond à 300 000 € lorsque les conditions du III sont satisfaites.','Le bénéfice comptable n’est pas directement “multiplié par 50 %”. Il faut d’abord déterminer le bénéfice fiscal de l’exploitation éligible puis appliquer le mécanisme d’abattement prévu par le CGI.'],bullets:['Séparer bénéfice comptable, résultat fiscal avant avantage et bénéfice ouvrant droit à l’abattement.','Documenter l’activité et la localisation.','Conserver le calcul extra-comptable et les pièces justifiant le taux.']},
      {title:'3. Renforcement temporaire à La Réunion en 2026',paragraphs:['La loi de finances pour 2026 a renforcé temporairement le dispositif pour certaines communes réunionnaises particulièrement défavorisées : le taux sur bénéfices y est porté à 80 % pour la période prévue par le texte.','Le renforcement concerne aussi la CFE et la TFPB selon leurs règles propres. Il faut donc traiter séparément impôt sur les bénéfices, CFE et taxe foncière.'],bullets:['IR : années 2025 à 2029.','IS : exercices clos à compter du 31 décembre 2025 et ouverts jusqu’au 31 décembre 2029.','CFE/TFPB : périodes spécifiques 2026-2030 à vérifier.']},
      {title:'4. Méthode de dossier',paragraphs:['Une note de travail ZFANG doit au minimum identifier l’établissement, l’activité principale, l’effectif, le chiffre d’affaires, la période, le régime d’imposition et le fondement du taux retenu.','Si un client a plusieurs établissements ou plusieurs activités, il faut éviter d’appliquer mécaniquement l’abattement à l’ensemble du résultat sans analyse de rattachement.'],bullets:['Créer une checklist annuelle.','Archiver la doctrine BOFiP applicable à l’exercice.','Rapprocher l’avantage de la liasse fiscale.']}
    ],
    decisionRules:[['Situation','Orientation','Contrôle clé'],['PME réunionnaise, activité éligible classique','Tester ZFANG 50 %','Taille + activité + bénéfice localisable.'],['Exploitation dans une commune renforcée 2026','Tester ZFANG 80 %','Adresse exacte + période d’application.'],['Activité mixte avec une branche non éligible','Analyse segmentée','Ne pas appliquer l’abattement global sans ventilation.'],['Client au micro','Ne pas écarter automatiquement','Le texte 2026 admet certains régimes micro ; contrôler les modalités.']],
    scenarios:[{title:'Commerce à Saint-Pierre',context:'Une société de 18 salariés et 3 M€ de CA exploite un commerce à Saint-Pierre.',reasoning:['La taille n’exclut pas le dispositif.','Vérifier l’activité exacte et sa correspondance avec les secteurs éligibles.','Vérifier si l’adresse entre dans une zone temporairement renforcée ou non.','Calculer l’abattement sur le bénéfice fiscal éligible et non sur le chiffre d’affaires.']},{title:'Deux établissements',context:'Une société possède un établissement réunionnais et une activité distincte en métropole.',reasoning:['Identifier le bénéfice provenant de l’exploitation réunionnaise.','Ne pas appliquer automatiquement l’abattement au résultat total.','Conserver une clé de ventilation défendable et cohérente.']}]});

  E('lodeom',{
    status:'Cours professionnel — barèmes 2026',
    comparison:[['Barème 2026','Zone d’exonération totale','Fin de l’exonération','Réflexe'],['Compétitivité / droit commun','Jusqu’à 1,3 SMIC','À 2,2 SMIC','<11 salariés ou secteurs éligibles selon règles.'],['Compétitivité renforcée','Jusqu’à 2 SMIC','À 2,7 SMIC','Tester secteur + taille + CA.'],['Innovation et croissance','Jusqu’à 1,7 SMIC','À 3,5 SMIC','Réservé aux situations prévues par le dispositif.']],
    courseSections:[
      {title:'1. Identifier le bon barème avant de calculer',paragraphs:['La LODEOM n’est pas une réduction uniforme. Le premier travail consiste à identifier le barème applicable en fonction du territoire, de l’effectif, du secteur d’activité et, selon les cas, du chiffre d’affaires.','À La Réunion, trois barèmes sont utilisés en 2026 : compétitivité de droit commun, compétitivité renforcée, innovation et croissance.'],bullets:['Moins de 11 salariés : le droit commun est un réflexe immédiat.','À partir de 11 salariés : contrôler le secteur d’activité.','Pour les barèmes renforcés : contrôler aussi les conditions spécifiques de taille/CA.']},
      {title:'2. Calcul annuel salarié par salarié',paragraphs:['L’exonération est calculée chaque année civile, pour chaque salarié et chaque contrat. La rémunération annuelle et le SMIC de référence sont donc déterminants.','Pour le barème de droit commun 2026, l’exonération est totale jusqu’à 1,3 SMIC puis dégressive jusqu’à extinction à 2,2 SMIC. La formule officielle utilise le paramètre T correspondant aux cotisations effectivement exonérables.'],bullets:['Droit commun : coefficient = 1,3 × T / 0,9 × (2,2 × SMIC annuel / rémunération annuelle brute − 1).','T maximal 2026 à La Réunion : 0,3201 pour <50 salariés et 0,3241 pour ≥50, sous réserve de la situation réelle du salarié.','Utiliser le simulateur Urssaf lorsque la paie présente des particularités.']},
      {title:'3. Les erreurs classiques en paie',paragraphs:['Une erreur de barème peut se propager sur douze mois de DSN. Il faut donc documenter l’éligibilité de l’employeur et recontrôler les seuils lorsqu’un effectif ou une activité évolue.','Le calcul n’est pas une simple remise fixe : la rémunération, les absences, la durée de travail et les paramètres de cotisations influencent le coefficient.'],bullets:['Ne pas reprendre un paramètre T d’une autre année.','Ne pas utiliser un SMIC théorique sans proratisation lorsque la situation l’exige.','Conserver la justification du secteur éligible.']},
      {title:'4. Conseil au client',paragraphs:['La LODEOM doit être intégrée dans les simulations d’embauche et d’augmentation salariale. Une hausse de salaire peut réduire progressivement l’exonération et modifier le coût marginal réel de l’augmentation.','Pour un prévisionnel, afficher le coût employeur avec et sans LODEOM permet de rendre l’avantage visible mais évite de le considérer comme permanent si les conditions peuvent changer.']}
    ],
    decisionRules:[['Situation','Action','Point de vigilance'],['Entreprise de 8 salariés','Tester droit commun','Quelle que soit l’activité, sous réserve des conditions communes.'],['Entreprise de 40 salariés tourisme','Comparer barème renforcé / droit commun','Secteur, CA, rémunération.'],['Rémunération proche d’un seuil','Calcul exact','Éviter les approximations en pourcentage.'],['Changement d’effectif ou d’activité','Revalider le barème','L’éligibilité peut évoluer.']],
    scenarios:[{title:'Restaurant de 8 salariés',context:'Un restaurant réunionnais embauche à 1,8 SMIC.',reasoning:['L’effectif <11 déclenche le réflexe droit commun.','L’exonération n’est plus totale à 1,8 SMIC : elle est dégressive.','Calculer avec le SMIC annuel et le paramètre T 2026.']},{title:'Hôtel de 60 salariés',context:'Un hôtel augmente plusieurs cadres.',reasoning:['Identifier le barème applicable au secteur.','Recalculer l’exonération salarié par salarié.','Mesurer le coût marginal des augmentations au-delà des seuils de dégressivité.']}]});

  E('tva-reunion',{
    status:'Cours professionnel — territorialité 2026',
    comparison:[['Flux','Principe','TVA à surveiller'],['Bien métropole → Réunion','Export / import pour la TVA','Importation à La Réunion + formalités douanières.'],['Bien Réunion → métropole','Export / import','Exonération export sous conditions + TVA à l’importation côté destination.'],['Service B2B métropole → Réunion','Lieu du preneur en règle générale','Taux réunionnais si le service est localisé à La Réunion, sauf exception.'],['Service B2C métropole → Réunion','Lieu du prestataire en règle générale','Taux métropolitain, sauf règles particulières.'],['Service B2B Réunion → métropole','Lieu du preneur en règle générale','Taux métropolitain, sauf exception.']],
    courseSections:[
      {title:'1. Séparer biens et services',paragraphs:['C’est la première distinction à faire. Pour les livraisons de biens, la métropole et les DOM sont traités comme des territoires distincts : les mouvements de biens sont gérés comme des exportations/importations.','Pour les prestations de services, les DOM ne sont pas considérés comme des territoires tiers en droit interne. On applique les règles de territorialité des services pour déterminer le lieu et donc le taux.'],bullets:['Bien : regarder départ, arrivée, importation et preuve d’export.','Service : regarder B2B/B2C puis les exceptions de territorialité.']},
      {title:'2. Prestations B2B : lieu du preneur',paragraphs:['En règle générale, une prestation fournie à un assujetti est imposée au lieu où le preneur est établi. Une prestation métropolitaine à un client assujetti réunionnais est donc normalement taxée au taux applicable à La Réunion lorsque le service y est localisé.','Dans les relations métropole/DOM, les mécanismes d’autoliquidation liés à un prestataire “non établi en France” ne s’appliquent pas de la même manière, car le DOM n’est pas territoire tiers pour les services.'],bullets:['Réunion : taux normal 8,5 % ; taux réduit principal 2,1 %.','Vérifier les services immobiliers, transports, accès à manifestations, travaux sur biens meubles, etc.']},
      {title:'3. Prestations B2C : lieu du prestataire, sauf exceptions',paragraphs:['Pour un consommateur non assujetti, la règle générale rattache la prestation au lieu du prestataire. Un prestataire métropolitain facturant un particulier réunionnais peut donc appliquer le taux métropolitain en règle générale.','Les services matériellement localisables et certaines prestations immatérielles suivent des règles particulières : l’analyse doit être faite avant d’appliquer mécaniquement 8,5 % ou 20 %.']},
      {title:'4. Déduction et justificatifs',paragraphs:['Le droit à déduction suppose une TVA légalement due et une dépense affectée à des opérations ouvrant droit à déduction. Une facture portant de la TVA au mauvais taux ne doit pas être traitée comme automatiquement déductible.','Pour les importations, rapprocher facture fournisseur, documents douaniers et TVA à l’importation. Pour les services, conserver les éléments justifiant le statut du client et le lieu d’établissement.']}
    ],
    decisionRules:[['Question','Si oui','Si non'],['Le flux porte-t-il sur un bien ?','Raisonner export/import','Passer aux règles de services.'],['Client assujetti ?','Règle B2B : lieu du preneur','Règle B2C : lieu du prestataire.'],['Règle spéciale 259 A / CIBS ?','Appliquer le critère spécial','Conserver la règle générale.'],['Facture au taux incohérent ?','Faire corriger / analyser avant déduction','Comptabiliser selon régime normal.']],
    scenarios:[{title:'Expertise métropole → SAS réunionnaise',context:'Un cabinet métropolitain facture une mission générale à une SAS de Saint-Pierre.',reasoning:['Relation B2B.','La règle générale localise la prestation au lieu du preneur.','Le taux applicable est celui de La Réunion, sauf règle particulière.','La facture doit être contrôlée avant enregistrement de TVA.']},{title:'Achat de marchandises en métropole',context:'Un commerçant réunionnais achète du stock expédié depuis Lyon.',reasoning:['Il s’agit d’un flux de biens.','Traiter la sortie de métropole et l’importation à La Réunion.','Rapprocher documents douaniers, octroi de mer éventuel et TVA import.']}]});

  E('244w',{
    status:'Cours professionnel — vérifié 2026',
    comparison:[['Point','244 quater W','Réflexe conseil'],['Bénéficiaire','Entreprise au réel / certaines entreprises exonérées','Identifier le régime d’imposition avant investissement.'],['Objet','Investissement productif neuf dans un DOM','Le bien doit servir une activité éligible.'],['Taux à La Réunion','38,25 % IR / 35 % IS','Calculer sur la base éligible, pas sur le prix TTC.'],['Base','Coût éligible HT retraité des aides publiques','Contrôler frais, aides, remplacement d’actifs.'],['Agrément','Selon nature/montant du projet','À vérifier avant engagement irréversible.']],
    courseSections:[
      {title:'1. Tester l’entreprise puis l’investissement',paragraphs:['Le crédit de l’article 244 quater W ne s’attache pas à n’importe quelle immobilisation achetée à La Réunion. Il faut d’abord que l’entreprise relève du champ, puis que l’activité et le bien soient éligibles.','Le texte vise notamment les investissements productifs neufs réalisés dans un DOM dans le cadre d’activités agricoles, industrielles, commerciales ou artisanales relevant des conditions prévues.'],bullets:['Régime réel ou régime expressément admis.','Bien productif neuf.','Affectation à une exploitation éligible dans le DOM.','Exclusions sectorielles à contrôler.']},
      {title:'2. Déterminer la base',paragraphs:['La base part du coût de l’investissement hors taxes et doit être retraitée selon les règles légales : certaines dépenses accessoires amortissables peuvent entrer dans la base, tandis que les aides publiques finançant le bien la diminuent.','Un investissement de remplacement peut nécessiter de retrancher la valeur de l’actif remplacé lorsqu’il a lui-même bénéficié d’un dispositif d’aide fiscale.'],bullets:['Tracer séparément prix du bien, transport, installation, mise en service, aides publiques.','Ne pas intégrer la TVA récupérable.','Archiver devis, factures et décision d’aide.']},
      {title:'3. Taux et fait générateur',paragraphs:['En 2026, le taux de référence du crédit est de 38,25 % pour une entreprise relevant de l’IR et 35 % pour une entreprise soumise à l’IS, sous réserve des règles particulières.','Le calendrier de réalisation et de mise en service est déterminant. Un dossier d’investissement doit être étudié avant la commande définitive lorsque des conditions d’agrément ou de chronologie s’appliquent.']},
      {title:'4. Comparer avec les autres dispositifs outre-mer',paragraphs:['Le conseil ne s’arrête pas au 244 quater W. Selon le porteur, le mode de détention et le schéma de financement, l’article 199 undecies B ou d’autres dispositifs peuvent être pertinents ou exclusifs.','La bonne pratique consiste à produire une note de choix de régime avant investissement : avantage brut, trésorerie, contraintes de conservation, agrément, rétrocession éventuelle et risque de reprise.']}
    ],
    decisionRules:[['Situation','Réflexe','Pourquoi'],['SAS réunionnaise à l’IS achète une machine neuve','Tester 244 W','Crédit de 35 % sur base éligible si toutes conditions remplies.'],['EI au réel achète du matériel productif','Tester 244 W + alternatives IR','Taux et mécanismes diffèrent.'],['Matériel d’occasion','Éligibilité très incertaine / généralement exclue du “neuf”','Ne pas calculer avant qualification.'],['Aide régionale finance une partie du bien','Réduire la base selon règles','Éviter la double prise en charge.']],
    scenarios:[{title:'Machine à 120 k€ HT',context:'Une SAS à l’IS reçoit 20 k€ d’aide publique pour une machine productive neuve.',reasoning:['Vérifier activité et bien éligibles.','Retraiter l’aide dans la base.','Calculer le crédit sur la base éligible après retraitements.','Vérifier agrément et calendrier avant conclusion.']},{title:'Projet locatif complexe',context:'Un investissement est porté par une structure puis loué à l’exploitant.',reasoning:['Ne pas appliquer automatiquement le 244 W.','Comparer avec 199 undecies B et les règles des schémas locatifs.','Identifier qui porte juridiquement l’investissement et qui bénéficie de l’avantage.']}]});

  E('cir',{
    status:'Cours professionnel — dossier technique 2026',
    comparison:[['Question','CIR','Ce qui ne suffit pas'],['Objet','Recherche fondamentale/appliquée ou développement expérimental','Simple nouveauté commerciale.'],['Critère central','Incertitude scientifique ou technique non résolue par l’état de l’art','Difficulté interne ou manque de compétence.'],['Preuve','État de l’art, hypothèses, essais, échecs, résultats','Une facture ou un cahier des charges seul.'],['Taux DOM','50 % jusqu’à 100 M€ de dépenses de recherche, puis 5 %','Ne pas confondre avec CII.']],
    courseSections:[
      {title:'1. Qualifier la R&D avant de chiffrer',paragraphs:['Le CIR repose d’abord sur la nature des travaux. Un projet doit chercher à lever une incertitude scientifique ou technique que les connaissances accessibles ne permettent pas de résoudre directement.','La nouveauté pour l’entreprise ou le caractère innovant d’un produit ne suffit pas. Il faut confronter le projet à l’état de l’art.'],bullets:['Définir le verrou scientifique/technique.','Documenter l’état de l’art avant les travaux.','Décrire la démarche expérimentale et les résultats.']},
      {title:'2. Construire l’assiette',paragraphs:['Après qualification des opérations, seules les dépenses rattachables aux travaux éligibles entrent dans l’assiette : notamment certaines dotations aux amortissements, dépenses de personnel de recherche et dépenses de sous-traitance sous conditions.','Les subventions publiques liées aux opérations de recherche doivent être retraitées selon les règles du crédit. Les temps du personnel doivent être documentés de manière cohérente avec les travaux décrits.']},
      {title:'3. Particularité DOM',paragraphs:['Pour les dépenses exposées dans une exploitation située dans un DOM, le premier taux du CIR est majoré à 50 % jusqu’au seuil légal de 100 M€ de dépenses, puis le taux de 5 % s’applique au-delà.','La localisation des dépenses doit être justifiable : personnel, établissement, moyens et opérations de recherche.']},
      {title:'4. Sécurisation et contrôle',paragraphs:['Un bon dossier CIR se prépare pendant le projet et non au moment du contrôle fiscal. Le dossier technique doit pouvoir relier chaque dépense à une opération décrite et à un verrou identifié.','Lorsque l’éligibilité technique est incertaine, un rescrit CIR ou une analyse spécialisée peut être pertinent avant dépôt.']}
    ],
    decisionRules:[['Situation','Orientation','Motif'],['Développement logiciel avec verrou algorithmique démontré','CIR à approfondir','Incertitude technique + démarche expérimentale.'],['Création d’une nouvelle interface utilisateur','Plutôt CII / hors CIR','Nouveauté fonctionnelle ≠ recherche.'],['Projet sans état de l’art','Dossier à sécuriser','Risque de rejet élevé.'],['Sous-traitance R&D','Vérifier prestataire et nature de dépense','Conditions spécifiques d’assiette.']],
    scenarios:[{title:'Algorithme de calcul inédit',context:'Une PME réunionnaise teste plusieurs méthodes car aucune solution connue n’atteint les performances requises.',reasoning:['Documenter l’état de l’art.','Formuler le verrou.','Tracer les essais, échecs et résultats.','Rattacher les temps et dépenses aux opérations.']},{title:'Application mobile classique',context:'L’entreprise développe une app avec des fonctions nouvelles pour ses clients mais utilisant des technologies standard.',reasoning:['La nouveauté commerciale ne suffit pas.','Absence probable de verrou scientifique ou technique.','Tester plutôt le CII si un produit nouveau et les autres critères sont réunis.']}]});

  E('cii',{
    status:'Cours professionnel — PME innovation 2026',
    comparison:[['Critère','CII','CIR'],['Bénéficiaire','PME au sens UE','Entreprises éligibles au CIR.'],['Objet','Prototype / installation pilote d’un produit nouveau','Travaux de R&D.'],['Nouveauté','Produit nouveau pour le marché avec performances supérieures','Incertitude scientifique ou technique.'],['Plafond','400 000 € de dépenses/an','Pas ce plafond spécifique.'],['Taux DOM 2026','60 %','50 % jusqu’à 100 M€ pour la première tranche.']],
    courseSections:[
      {title:'1. Produit nouveau : comparaison au marché',paragraphs:['Le CII ne récompense pas toute amélioration interne. Il faut caractériser un produit nouveau pour le marché de référence, présentant des performances supérieures mesurables sur le plan technique, de l’éco-conception, de l’ergonomie ou des fonctionnalités.','Le marché pertinent doit être défini et documenté : concurrents, produits comparables, performances existantes.']},
      {title:'2. Prototypes et installations pilotes',paragraphs:['Les dépenses doivent se rattacher à la conception de prototypes ou d’installations pilotes du nouveau produit. La production courante, le marketing, la commercialisation ou les modifications de routine n’entrent pas dans la même logique.','Le dossier doit relier les dépenses aux travaux de conception du prototype.']},
      {title:'3. Taux DOM et plafond',paragraphs:['En 2026, le CII est calculé dans la limite annuelle de 400 000 € de dépenses éligibles. Pour les dépenses exposées dans les DOM, le taux majoré est de 60 %.','À plafond plein, l’avantage théorique peut donc être très significatif ; cette importance justifie une documentation technique et comptable robuste.']},
      {title:'4. Frontière CIR/CII',paragraphs:['Un même projet peut comporter une phase de R&D relevant du CIR et une phase ultérieure de conception de prototype relevant du CII, mais les mêmes dépenses ne doivent pas être comptées deux fois.','Le dossier doit séparer chronologie, objectifs, équipes et dépenses.']}
    ],
    decisionRules:[['Situation','Orientation','Contrôle'],['Produit nouveau avec performances supérieures mesurables','CII à tester','PME + prototype + marché.'],['Simple nouvelle version commerciale','Probablement hors CII','Vérifier réelle nouveauté produit.'],['Verrou technique non résolu','Tester CIR avant CII','Nature R&D.'],['Projet mixte R&D puis prototype','Ventiler CIR/CII','Pas de double comptage.']],
    scenarios:[{title:'Nouveau dispositif connecté',context:'Une PME conçoit un dispositif plus économe et plus ergonomique que les produits existants.',reasoning:['Définir le marché de comparaison.','Mesurer les performances supérieures.','Identifier les dépenses de prototype.','Calculer le CII DOM dans le plafond.']},{title:'Ajout d’une fonctionnalité',context:'Une entreprise ajoute un tableau de bord standard à son logiciel.',reasoning:['Vérifier si le produit est réellement nouveau pour le marché.','Une simple fonctionnalité supplémentaire n’est pas suffisante.']}]});

  E('credit-famille',{
    status:'Cours professionnel — vérifié 11/08/2026',
    comparison:[['Dépense','Taux','Exemple'],['Crèche / halte-garderie pour enfants <3 ans','50 %','Création, fonctionnement ou financement d’un établissement éligible.'],['Aide financière services à la personne / CESU éligible','25 %','Aide accordée aux salariés selon les règles légales.'],['Plafond du crédit','500 000 €/an par entreprise','Après calcul des catégories éligibles.']],
    courseSections:[
      {title:'1. Entreprises et personnes concernées',paragraphs:['Le crédit d’impôt famille est ouvert aux entreprises relevant d’un régime réel d’imposition, à l’IR ou à l’IS, quelle que soit la nature de leur activité. Les micro-entreprises n’y ont pas accès.','Les dépenses visent principalement les salariés ; certains non-salariés peuvent être concernés lorsque l’entreprise emploie du personnel et applique les mêmes règles d’attribution.']},
      {title:'2. Deux catégories, deux taux',paragraphs:['Les dépenses de création ou de fonctionnement d’établissements accueillant les enfants de moins de trois ans ouvrent droit au taux de 50 %. Les aides financières éligibles versées pour certains services à la personne ouvrent droit au taux de 25 %.','Les aides et subventions reçues au titre des mêmes dépenses doivent être intégrées au calcul selon les règles applicables.']},
      {title:'3. Plafond et déclaration',paragraphs:['Le crédit est plafonné à 500 000 € par an et par entreprise. Il s’impute sur l’IR ou l’IS dû au titre de l’année des dépenses.','La détermination se formalise notamment via le formulaire 2069-FA-SD. Il faut conserver les conventions, factures, critères d’attribution et justificatifs des bénéficiaires.']},
      {title:'4. Politique RH et égalité de traitement',paragraphs:['La dépense doit être organisée comme un dispositif de l’entreprise et non comme une faveur informelle à un seul dirigeant. Pour les non-salariés, l’accès suppose notamment que l’entreprise emploie des salariés et que les règles soient communes.','Le conseil fiscal doit donc être couplé à une vérification sociale et RH du dispositif.']}
    ],
    decisionRules:[['Situation','Traitement à tester','Taux'],['Financement place en crèche','Catégorie crèche','50 %'],['CESU préfinancé éligible','Aide financière','25 %'],['Micro-entreprise','Pas de crédit famille','Régime réel requis'],['Dirigeant seul sans salarié','Vigilance forte','Conditions du personnel non salarié non remplies en principe.']],
    scenarios:[{title:'PME finance une crèche',context:'Une société finance plusieurs berceaux pour ses salariés.',reasoning:['Vérifier l’établissement éligible.','Identifier les dépenses nettes d’aides.','Appliquer le taux de 50 %.','Contrôler le plafond annuel.']},{title:'CESU pour salariés et dirigeant',context:'La société verse une aide uniforme à ses salariés et à son dirigeant.',reasoning:['Tester la catégorie 25 %.','Vérifier que les conditions d’attribution aux non-salariés sont respectées.','Formaliser la politique d’entreprise.']}]});

  E('assiette-tns-2026',{
    status:'Cours professionnel — réforme 2026',
    comparison:[['Avant / après','Ancienne logique','Réforme appliquée en 2026'],['Assiette cotisations','Ancienne base fiscale/sociale avec retraitements','Revenu brut social puis abattement forfaitaire de 26 %.'],['CSG-CRDS','Base incluant des mécanismes distincts','Assiette unifiée avec les cotisations.'],['Objectif','Prélèvements moins lisibles','Plus de cotisations contributives, notamment retraite.']],
    courseSections:[
      {title:'1. Ce qui change',paragraphs:['La réforme est mise en œuvre en 2026 lors de la régularisation des cotisations portant sur les revenus 2025. Elle crée une assiette unique pour les cotisations et la CSG-CRDS.','Cette assiette part d’un revenu brut social auquel est appliqué un abattement forfaitaire de 26 %, qui remplace l’ancien mécanisme de déduction des cotisations.']},
      {title:'2. Société à l’IS : ne pas regarder seulement la rémunération',paragraphs:['Pour un dirigeant TNS d’une société à l’IS, le revenu social doit intégrer les éléments prévus par les textes, notamment la rémunération et, selon les règles applicables, une fraction de certains dividendes.','L’arbitrage rémunération/dividendes d’une EURL ou d’une SARL majoritaire doit donc être recalculé avec les paramètres 2026.']},
      {title:'3. Comparaison avec la SAS',paragraphs:['Comparer un TNS et un président assimilé salarié exige un même objectif de revenu net. Comparer simplement “45 % contre 70 % de charges” est insuffisant et souvent trompeur.','Il faut intégrer coût employeur, net avant IR, retraite, prévoyance, dividendes et besoins de trésorerie de la société.']},
      {title:'4. Mise en œuvre au cabinet',paragraphs:['Les anciennes feuilles de calcul doivent être millésimées. Toute simulation EURL/SARL réalisée avec une formule antérieure à la réforme peut conduire à une recommandation erronée.','Le bon livrable est une simulation de revenu global sur plusieurs hypothèses de rémunération et de distribution.']}
    ],
    decisionRules:[['Cas','Réflexe'],['Simulation SARL 2026','Utiliser nouvelle assiette et barèmes 2026.'],['Dividendes importants','Contrôler le seuil social et leur intégration.'],['Comparatif SAS/SARL','Comparer à net équivalent et couverture comparable.'],['Ancien fichier Excel 2024','Ne pas réutiliser sans mise à jour.']],
    scenarios:[{title:'Gérant majoritaire',context:'Un gérant veut 4 000 € net mensuels et 30 000 € de dividendes.',reasoning:['Calculer la rémunération dans le nouveau cadre 2026.','Tester la fraction de dividendes entrant dans l’assiette.','Comparer avec une SAS à revenu net équivalent.']}]});

  E('resultat-fiscal',{
    status:'Cours professionnel — fondamentaux de liasse',
    comparison:[['Nature','Comptabilité','Fiscalité'],['Charge déductible','En charge','Pas de retraitement.'],['Charge non déductible','En charge','Réintégration extra-comptable.'],['Produit non imposable','En produit','Déduction extra-comptable.'],['Décalage temporaire','Comptabilisé selon règles','Retraitement puis reprise future.']],
    courseSections:[
      {title:'1. La logique du passage comptable → fiscal',paragraphs:['Le résultat comptable mesure la performance selon les règles comptables. Le résultat fiscal applique ensuite les règles du CGI : certaines charges comptables ne sont pas déductibles et certains produits ne sont pas imposables.','Le travail fiscal consiste donc à qualifier chaque différence et non à “corriger” la comptabilité.']},
      {title:'2. Réintégrations',paragraphs:['Une réintégration augmente le résultat fiscal par rapport au résultat comptable. Elle concerne par exemple des charges comptablement justifiées mais fiscalement exclues ou plafonnées.','Exemples classiques : amendes et pénalités, fraction non déductible de certaines charges, provisions non admises, dépenses personnelles ou somptuaires selon le cas.']},
      {title:'3. Déductions',paragraphs:['Une déduction extra-comptable réduit le résultat fiscal lorsque le produit comptabilisé n’est pas imposable ou lorsqu’un régime fiscal prévoit un avantage calculé hors comptabilité.','Les exonérations zonées ou certains régimes particuliers doivent être rapprochés de la liasse et documentés séparément.']},
      {title:'4. Dossier de révision',paragraphs:['Chaque retraitement doit avoir une pièce ou une note de justification et être reconductible ou soldé correctement l’année suivante lorsqu’il est temporaire.','Une bonne feuille de travail distingue différences permanentes, temporaires, avantages fiscaux et déficits reportables.']}
    ],
    decisionRules:[['Question','Réponse oui','Conséquence'],['Charge comptable fiscalement non déductible ?','Oui','Réintégrer.'],['Produit comptable exonéré ?','Oui','Déduire.'],['Différence temporaire ?','Oui','Prévoir le suivi N+1.'],['Régime de faveur applicable ?','Oui','Calcul séparé + justificatifs.']],
    scenarios:[{title:'Clôture PME',context:'Le compte de charges contient amendes, véhicule, provision litigieuse et dépenses personnelles.',reasoning:['Qualifier comptablement chaque écriture.','Identifier les charges fiscalement exclues ou limitées.','Réintégrer sans modifier une comptabilisation correcte.','Documenter les montants dans la feuille de passage.']}]});

  E('provisions',{
    status:'Cours professionnel — art. 39 CGI',
    comparison:[['Condition','Question','Conséquence si non'],['Charge/perte déductible par nature','Serait-elle déductible si elle était certaine ?','Provision non déductible.'],['Risque nettement précisé','Objet individualisé ?','Provision non déductible.'],['Probabilité','Perte/charge probable à la clôture ?','Simple éventualité = non.'],['Fait générateur','Événement existant à la clôture ?','Pas de déduction anticipée.'],['Évaluation','Montant estimable avec méthode sérieuse ?','Risque de rejet.']],
    courseSections:[
      {title:'1. Provision comptable ≠ provision fiscale',paragraphs:['La comptabilité peut conduire à constater un risque conformément au principe de prudence, mais la déduction fiscale obéit à des conditions spécifiques. Une provision comptabilisée peut donc devoir être réintégrée.','Le contrôle fiscal porte autant sur la réalité du risque que sur son évaluation et sa date d’existence.']},
      {title:'2. Les cinq questions de contrôle',paragraphs:['Le cabinet doit vérifier successivement la nature de la charge, la précision du risque, sa probabilité, l’existence de faits à la date de clôture et la qualité de l’estimation.','Si une seule condition fiscale essentielle manque, la provision peut être non déductible.']},
      {title:'3. Documentation',paragraphs:['Un litige doit être appuyé par courriers, contrats, échanges d’avocats, historique des réclamations et méthode d’évaluation. Une provision clients doit être fondée sur des indices de dépréciation individualisés.','Les pourcentages forfaitaires non justifiés sont particulièrement fragiles.']},
      {title:'4. Reprise',paragraphs:['Une provision déduite doit être suivie jusqu’à sa reprise. Lorsque le risque disparaît ou se réalise, la reprise comptable et son traitement fiscal doivent être cohérents avec le traitement antérieur.']}
    ],
    decisionRules:[['Situation','Traitement probable'],['Litige documenté, perte probable, estimation fiable','Provision potentiellement déductible.'],['Risque commercial vague','Réintégration.'],['Charge future décidée après clôture','Pas de provision fiscale au titre de N.'],['Provision statistique sans base sérieuse','Risque élevé de non-déductibilité.']],
    scenarios:[{title:'Procès en cours',context:'Assignation reçue avant clôture, avocat estime une perte probable de 40 à 60 k€.',reasoning:['Le fait existe à la clôture.','Le risque est individualisé.','La probabilité est documentée.','Retenir une estimation défendable et conserver l’avis juridique.']}]});

  E('cfe-creation',{
    status:'Cours professionnel — CFE 2026',
    comparison:[['Moment','Principe','Action cabinet'],['Année de création','Pas de CFE','Déposer la déclaration initiale si nécessaire.'],['Année suivante','Imposition possible','Contrôler base, minimum et exonérations.'],['Très faible CA','Exonération de cotisation minimum si CA/recettes ≤ 5 000 €','Vérifier autres éléments de CFE.'],['Zone / activité particulière','Exonération ou abattement possible','Tester ZFANG et autres régimes.']],
    courseSections:[
      {title:'1. Année civile de création',paragraphs:['La CFE n’est pas due pour l’année civile au cours de laquelle l’établissement est créé. Cette règle n’est pas liée à la date de clôture comptable.','Une création au 31 décembre bénéficie donc de l’exonération pour cette année, mais peut être imposée dès l’année suivante.']},
      {title:'2. Base d’imposition et cotisation minimum',paragraphs:['La CFE repose en principe sur la valeur locative des biens passibles d’une taxe foncière utilisés pour l’activité. Lorsque cette base est faible, une cotisation minimum peut s’appliquer selon le chiffre d’affaires et les délibérations locales.','Les entreprises dont le CA ou les recettes n’excèdent pas 5 000 € bénéficient de l’exonération de cotisation minimum prévue par les textes.']},
      {title:'3. Exonérations zonées et sectorielles',paragraphs:['La première année n’est qu’un niveau de contrôle. Il faut ensuite tester les exonérations permanentes, temporaires ou facultatives liées à l’activité ou à la zone. À La Réunion, la ZFANG peut modifier la CFE sous ses propres conditions.']},
      {title:'4. Réflexe de création',paragraphs:['Le dossier permanent doit contenir la date d’ouverture de chaque établissement, l’adresse, la surface utilisée, la situation de domiciliation et la déclaration initiale. Un déménagement ou une création secondaire peut créer une nouvelle problématique de CFE.']}
    ],
    decisionRules:[['Situation','Réflexe'],['Création en cours d’année','Pas de CFE pour cette année civile.'],['Premier avis CFE N+1','Contrôler base et commune.'],['CA très faible','Tester exonération de cotisation minimum.'],['Établissement en zone ZFANG renforcée','Tester l’abattement CFE spécifique.']],
    scenarios:[{title:'Création le 20 décembre',context:'Une SAS démarre son activité le 20/12/2026.',reasoning:['Pas de CFE 2026.','Préparer la situation 2027.','Vérifier déclaration initiale et éventuels dispositifs zonés.']}]});

  E('is-taux',{
    status:'Cours professionnel — IS 2026',
    comparison:[['Tranche','Taux','Conditions'],['Bénéfice normal','25 %','Taux de droit commun.'],['Premiers 42 500 €','15 %','PME éligible, période de 12 mois.'],['Au-delà de 42 500 €','25 %','Même si le taux réduit s’applique à la première tranche.']],
    courseSections:[
      {title:'1. Taux normal',paragraphs:['Le taux normal de l’IS est de 25 %. Il s’applique au résultat fiscal après retraitements, déficits imputables et éventuels régimes spécifiques.','Le calcul de l’IS ne doit donc jamais être fait directement sur le résultat comptable sans passage fiscal.']},
      {title:'2. Taux réduit PME',paragraphs:['Le taux de 15 % s’applique à la première tranche de 42 500 € de bénéfice par période de douze mois lorsque les conditions sont remplies.','Il faut notamment contrôler le chiffre d’affaires, la libération intégrale du capital et la structure de détention du capital.']},
      {title:'3. Périodes courtes ou longues',paragraphs:['Le plafond de la tranche réduite est lié à une période de douze mois. Une durée d’exercice inhabituelle impose de vérifier la proratisation applicable.']},
      {title:'4. Ordre des opérations',paragraphs:['Le calcul pratique suit une logique : résultat fiscal → imputation des déficits → application des régimes de faveur → ventilation des tranches d’IS → crédits et réductions d’impôt.','Cette chronologie évite de confondre réduction de base, réduction d’impôt et crédit d’impôt.']}
    ],
    decisionRules:[['Condition','Si satisfaite','Sinon'],['CA dans la limite PME','Poursuivre le test 15 %','25 % normal.'],['Capital totalement libéré','Poursuivre','Pas de taux réduit.'],['Détention ≥75 % selon conditions','Appliquer 15 % sur tranche si toutes conditions','25 %.']],
    scenarios:[{title:'Bénéfice 80 k€',context:'PME remplissant toutes les conditions, exercice de 12 mois.',reasoning:['42 500 € à 15 %.','37 500 € à 25 %.','Puis imputer crédits/réductions d’impôt selon leurs règles.']}]});

  E('deficits-is',{
    status:'Cours professionnel — déficits IS 2026',
    comparison:[['Mécanisme','Portée','Limite principale'],['Report en avant','Sans limite de durée en principe','Imputation annuelle plafonnée à 1 M€ + 50 % du bénéfice excédant 1 M€.'],['Carry-back','Sur bénéfice de l’exercice précédent','Option, déficit reporté en arrière limité à 1 M€ et autres règles.']],
    courseSections:[
      {title:'1. Stock de déficits',paragraphs:['Un déficit fiscal d’une société à l’IS n’est pas une créance immédiatement remboursable. Il constitue en principe un stock reportable qui pourra réduire des bénéfices futurs dans les limites légales.','Le cabinet doit suivre ce stock par millésime, événements affectant le droit au report et imputations réalisées.']},
      {title:'2. Plafond d’imputation',paragraphs:['Le bénéfice d’un exercice peut être absorbé par des déficits antérieurs dans la limite de 1 M€ plus 50 % de la fraction du bénéfice qui dépasse 1 M€. Le solde non utilisé demeure en principe reportable.','Ce plafond devient particulièrement important dans les exercices de fort rebond.']},
      {title:'3. Carry-back',paragraphs:['Le report en arrière est optionnel et concerne le déficit de l’exercice dans la limite prévue, sur le bénéfice de l’exercice précédent répondant aux conditions. Il génère une créance fiscale selon les règles applicables.','L’intérêt dépend de la trésorerie, de l’IS payé antérieurement et des perspectives futures.']},
      {title:'4. Événements sensibles',paragraphs:['Cessation, changement d’activité réelle, fusion ou restructuration peuvent affecter le maintien des déficits. Un stock ancien ne doit jamais être repris dans une simulation sans examen du dossier juridique et fiscal.']}
    ],
    decisionRules:[['Situation','Réflexe'],['Déficit avec bénéfices futurs probables','Report en avant.'],['IS payé en N-1 et déficit en N','Tester carry-back.'],['Restructuration / changement d’activité','Audit du maintien des déficits.'],['Gros bénéfice après plusieurs déficits','Appliquer le plafond annuel.']],
    scenarios:[{title:'Rebond à 1,5 M€',context:'La société a un stock de 2 M€ de déficits et réalise 1,5 M€ de bénéfice.',reasoning:['Plafond classique : 1 M€ + 50 % de 0,5 M€ = 1,25 M€ imputables.','250 k€ restent imposables avant autres retraitements.','Le solde du stock reste à suivre.']}]});

  E('octroi-mer',{
    status:'Cours professionnel — réforme 2026',
    comparison:[['Situation','Octroi de mer','Réflexe'],['Importation à La Réunion','Opération dans le champ','Identifier nomenclature et taux OM/OMR.'],['Production locale, CA production < 550 k€ N-1','Producteur hors assujettissement de l’art. 2 selon seuil','Contrôler régime exact et obligations.'],['Production locale, CA production ≥ 550 k€ N-1','Assujetti','Déclarer selon règles et taux.'],['Transformation','Changement de classement SH4 notamment','Qualifier l’activité de production.']],
    courseSections:[
      {title:'1. Deux portes d’entrée : importation et production locale',paragraphs:['L’octroi de mer s’applique aux importations de biens et aux livraisons à titre onéreux de biens produits localement par les personnes assujetties. Il se raisonne indépendamment de la TVA.','Le dossier d’achat doit donc distinguer TVA, octroi de mer, octroi de mer régional et droits éventuels.']},
      {title:'2. Seuil producteur local 2026',paragraphs:['Depuis le 21 février 2026, le seuil d’assujettissement des producteurs locaux est fixé à 550 000 € de chiffre d’affaires de production de l’année civile précédente. Il s’apprécie hors TVA et hors octroi de mer.','En début d’activité, le seuil est ajusté au prorata du temps d’exploitation dans les conditions légales.']},
      {title:'3. Qualification de production',paragraphs:['La production comprend fabrication, transformation, rénovation, activités extractives et activités agricoles visées. Pour certaines transformations, le changement de position tarifaire au niveau SH4 est un critère déterminant.','Le code douanier n’est donc pas qu’un sujet d’import : il peut déterminer si une opération locale constitue une transformation au sens du dispositif.']},
      {title:'4. Taux et exonérations',paragraphs:['Les taux d’octroi de mer et d’octroi de mer régional sont fixés par produit et territoire. On ne peut pas mémoriser un taux unique. Le classement douanier et les délibérations locales doivent être consultés.','Pour un devis ou un prix de revient, simuler l’octroi de mer avant de fixer la marge évite des erreurs significatives.']}
    ],
    decisionRules:[['Question','Action'],['Bien importé ?','Chercher nomenclature + taux OM/OMR + exonération.'],['Bien produit localement ?','Tester activité de production et seuil 550 k€.'],['Transformation ?','Contrôler changement SH4 et définition légale.'],['Prix de vente à déterminer ?','Intégrer OM/OMR dans coût complet.']],
    scenarios:[{title:'Atelier local',context:'Un fabricant réunionnais réalise 620 k€ de CA de production en N-1.',reasoning:['Le seuil 550 k€ est dépassé.','Vérifier les livraisons locales imposables et les taux par produits.','Mettre en place le suivi déclaratif.']},{title:'Importateur',context:'Un commerce importe des appareils électroniques.',reasoning:['Identifier le code douanier.','Calculer droits, OM, OMR et TVA import selon le dossier.','Intégrer ces éléments au coût de revient.']}]});

  E('micro-2026',{
    status:'Cours professionnel — seuils 2026',
    comparison:[['Activité','Seuil micro 2026'],['Commerce / hébergement hors cas spécifiques','203 100 €'],['Prestations BIC','83 600 €'],['BNC','83 600 €'],['Meublé de tourisme classé / chambre d’hôtes','83 600 €'],['Meublé de tourisme non classé','15 000 €']],
    courseSections:[
      {title:'1. Le micro est un régime fiscal, pas une forme juridique',paragraphs:['Le régime micro simplifie la détermination du bénéfice imposable par un abattement forfaitaire sur le chiffre d’affaires. Il ne doit pas être confondu avec le statut juridique de l’entreprise individuelle ni avec la franchise en base de TVA.','Un entrepreneur peut sortir de la franchise TVA tout en restant au micro-fiscal, ou inversement selon les seuils applicables.']},
      {title:'2. Règle N-1 / N-2',paragraphs:['Pour bénéficier du micro en N, le CA de N-1 ou de N-2 doit respecter le seuil applicable. La sortie intervient lorsque le seuil a été dépassé deux années consécutives dans les conditions prévues.','Un dépassement isolé ne suffit donc pas automatiquement à faire sortir du micro l’année suivante.']},
      {title:'3. Activités mixtes',paragraphs:['Lorsque plusieurs activités sont exercées, il faut contrôler le seuil global et, selon les combinaisons, les sous-seuils propres aux différentes activités.','La ventilation du chiffre d’affaires par nature doit être fiable et suivie dès la tenue comptable.']},
      {title:'4. Le bon conseil n’est pas toujours “rester micro”',paragraphs:['Le micro peut devenir défavorable lorsque les charges réelles, investissements, TVA récupérable ou besoins de financement dépassent l’avantage de simplicité. Le cabinet doit comparer revenu net, cotisations, TVA et obligations comptables.','Le choix peut être volontairement orienté vers un régime réel même avant le dépassement des seuils lorsque l’économie du client le justifie.']}
    ],
    decisionRules:[['Situation','Réflexe'],['Prestataire à 80 k€','Micro possible sous réserve N-1/N-2','Comparer avec réel.'],['Prestataire à 90 k€ une seule année','Pas de sortie automatique','Regarder l’autre année de référence.'],['Forte structure de coûts','Simuler le réel','Abattement forfaitaire peut être insuffisant.'],['Gros investissements avec TVA','Séparer analyse micro et TVA','La franchise TVA est un sujet distinct.']],
    scenarios:[{title:'Consultant à 82 k€',context:'CA 2025 = 82 k€, CA 2024 = 70 k€.',reasoning:['Le seuil services 2026 est 83 600 €.','Les années de référence restent sous seuil.','Le micro est possible, mais il faut comparer avec les charges réelles.']},{title:'Dépassement ponctuel',context:'CA services 2025 = 90 k€, 2024 = 70 k€.',reasoning:['Un seul dépassement ne fait pas sortir automatiquement.','Suivre 2026 : un second dépassement consécutif entraînerait la sortie selon les règles.']}]});

  E('zrr-historique-reunion',{
    status:'Cours professionnel — dossiers historiques',
    comparison:[['Période','Exonération ZRR historique'],['Jusqu’au terme du 59e mois','100 %'],['12 mois suivants','75 %'],['12 mois suivants','50 %'],['12 mois suivants','25 %']],
    courseSections:[
      {title:'1. Pourquoi la ZRR existe encore dans des dossiers 2026',paragraphs:['La ZRR historique a ouvert des droits pour certaines créations/reprises antérieures. Même si le dispositif n’est plus le régime courant à La Réunion, un dossier ancien peut encore produire des effets dégressifs selon sa date exacte de départ.','Le premier réflexe est donc de reconstituer la date de création/reprise et l’option exercée.']},
      {title:'2. Dégressivité',paragraphs:['Le régime prévoyait une exonération totale jusqu’au terme du 59e mois suivant la création ou la reprise puis trois périodes annuelles à 75 %, 50 % et 25 %.','Le calendrier doit être construit mois par mois lorsque la date de départ n’est pas le 1er janvier.']},
      {title:'3. Concurrence avec d’autres régimes',paragraphs:['Lorsque plusieurs régimes zonés étaient ouverts, l’option pouvait être irrévocable et emporter renonciation aux autres dispositifs visés. Il est donc dangereux d’affirmer qu’une entreprise “passe en ZFANG après cinq ans”.','Relire l’option et la doctrine de l’année d’origine avant toute correction.']}
    ],
    decisionRules:[['Dossier','Action'],['Création/reprise ancienne avec mention ZRR','Reconstituer calendrier et option.'],['Fin des 5 ans','Appliquer dégressivité si droit encore ouvert.'],['Client demande passage ZFANG','Vérifier irrévocabilité / renonciation initiale.']],
    scenarios:[{title:'Création décembre 2018',context:'Le dossier montre encore un abattement en 2026.',reasoning:['C’est potentiellement cohérent avec la fin de la période dégressive.','Reconstituer le calendrier exact.','Vérifier la décision initiale et les textes transitoires.']}]});

  E('frr-zsar-reunion',{
    status:'Cours professionnel — zonage 2026',
    comparison:[['Notion','À La Réunion en 2026'],['FRR','Zonage géographique repris de la ZSAR.'],['Exonération FRR art. 44 quindecies A','Ne s’applique pas aux nouvelles entreprises réunionnaises selon la doctrine, compte tenu du régime ZFANG.'],['ZFANG','Régime fiscal spécifique à tester pour une exploitation réunionnaise.'],['ZRR historique','Peut encore concerner d’anciens droits.']],
    courseSections:[
      {title:'1. Le piège du mot “FRR”',paragraphs:['Certaines communes ou portions de communes réunionnaises apparaissent dans le zonage FRR/ZSAR. Cela ne signifie pas qu’une création 2026 bénéficie du régime métropolitain d’exonération FRR sur les bénéfices.','La doctrine 2026 précise que l’exonération FRR/FRR+ ne s’applique pas dans les zones de La Réunion en présence du régime spécifique ZFANG.']},
      {title:'2. Utilité du zonage',paragraphs:['Le zonage reste utile pour comprendre des dossiers historiques, identifier les Hauts et lire certains textes. Il peut aussi être nécessaire pour d’autres aides ou dispositifs non identiques à l’exonération de bénéfices.','Il faut toujours identifier le texte précis qui renvoie au zonage au lieu de déduire un avantage fiscal du seul code postal.']},
      {title:'3. Dossier 2026',paragraphs:['Pour une création en 2026, le bon ordre est : adresse exacte → activité → taille → ZFANG → autres aides éventuelles. Ne pas appliquer le tableau “5 ans à 100 %, puis 75/50/25” du FRR général.']}
    ],
    decisionRules:[['Situation','Réponse'],['Création 2026 dans les Hauts','Tester ZFANG, pas exonération FRR automatique.'],['Ancien dossier ZRR','Analyser droits historiques séparément.'],['Aide utilisant la notion ZSAR','Lire son texte propre.']],
    scenarios:[{title:'Création dans les Hauts de Saint-Pierre',context:'Le client demande cinq ans d’exonération car son adresse apparaît en FRR.',reasoning:['Le zonage seul ne suffit pas.','L’exonération FRR sur bénéfices n’est pas le régime applicable à La Réunion en 2026.','Tester la ZFANG et ses propres conditions.']}]});

  KB.flashcards.push(
    ['LODEOM droit commun 2026 : exonération totale jusqu’à ?','1,3 SMIC, puis dégressive jusqu’à 2,2 SMIC.'],
    ['TVA services B2B métropole/La Réunion : principe de lieu ?','Lieu d’établissement du preneur, sauf règles particulières.'],
    ['Octroi de mer : seuil producteur local 2026 ?','550 000 € de CA de production N-1.'],
    ['Micro services 2026 : seuil ?','83 600 €.'],
    ['Micro commerce 2026 : seuil ?','203 100 €.'],
    ['Provision fiscale : une simple éventualité suffit-elle ?','Non, le risque doit être probable et suffisamment précisé.']
  );
})();
